accounts:
  - name: jean
    coins: ["20000token", "200000000stake"]
  - name: caro
    coins: ["10000token", "100000000stake", "1000000steak"]
validator:
  name: jean
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: caro
  coins: ["5token", "100000stake", "500000steak"]
